# Generated by Django 5.2.5 on 2025-08-19 08:24

import django.db.models.constraints
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalizationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=100)),
                ('date_format', models.CharField(default='dd:mm:yyyy', max_length=32)),
                ('time_format', models.CharField(default='hh:mm:ss a', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='PG Admin owner of these localization settings', on_delete=django.db.models.deletion.CASCADE, related_name='accounts_localizationsettings_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['owner_id', '-created_at'],
                'indexes': [models.Index(fields=['owner'], name='idx_localizationsettings_owner')],
                'constraints': [models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('owner',), name='uniq_localizationsettings_owner')],
            },
        ),
    ]
