# Generated by Django 5.2.5 on 2025-08-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_localizationsettings'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='localizationsettings',
            name='uniq_localizationsettings_owner',
        ),
        migrations.AddConstraint(
            model_name='localizationsettings',
            constraint=models.UniqueConstraint(fields=('owner',), name='uniq_localizationsettings_owner'),
        ),
    ]
