# Generated by Django 5.2.5 on 2025-08-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_email_otp_user_email_otp_attempts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('role', models.CharField(choices=[('pg_admin', 'PG Admin'), ('pg_staff', 'PG Staff')], default='pg_admin', max_length=20)),
                ('password_hash', models.CharField(max_length=128)),
                ('email_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('email_otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('email_otp_last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_otp_attempts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
