# Generated by Django 5.2.5 on 2025-08-22 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_pendingregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingregistration',
            name='pg_admin',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'pg_admin'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_staff_registrations', to=settings.AUTH_USER_MODEL),
        ),
    ]
