# Generated by Django 5.2.5 on 2025-08-25 14:19

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_pendingregistration_pg_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Profile picture of the user', null=True, upload_to=accounts.models.profile_picture_upload_to),
        ),
    ]
