# Generated by Django 5.2.5 on 2025-08-28 18:41

import accounts.models
import tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Profile picture of the user', null=True, upload_to=accounts.models.profile_picture_upload_to, validators=[tenants.models.validate_file_size]),
        ),
    ]
