# Generated by Django 5.2.5 on 2025-08-15 18:59

import django.core.validators
import django.db.models.deletion
import tenants.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0003_bed_monthly_rent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits', regex='^\\d{10}$')])),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address_line', models.CharField(blank=True, max_length=400)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('pincode', models.CharField(blank=True, max_length=6, validators=[django.core.validators.RegexValidator(message='PIN code must be exactly 6 digits', regex='^\\d{6}$')])),
                ('id_proof_type', models.CharField(blank=True, help_text='e.g., Aadhaar, PAN, Passport', max_length=50)),
                ('id_proof_number', models.CharField(blank=True, max_length=100)),
                ('id_proof_document', models.FileField(blank=True, help_text='Upload an image (max 10 MB) or PDF (max 2 MB) for ID proof', null=True, upload_to='tenants/id_proofs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf']), tenants.models.validate_file_size])),
                ('photo', models.ImageField(blank=True, null=True, upload_to='tenants/photos/', validators=[tenants.models.validate_file_size])),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name', 'phone'],
            },
        ),
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('active', 'Active / Checked-in'), ('completed', 'Completed / Checked-out'), ('canceled', 'Canceled')], default='reserved', max_length=12)),
                ('check_in', models.DateField()),
                ('expected_check_out', models.DateField(blank=True, null=True)),
                ('actual_check_out', models.DateField(blank=True, null=True)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('maintenance_amount', models.DecimalField(decimal_places=2, default=0, help_text='One-time or recurring maintenance charge applicable for this stay', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stays', to='properties.bed')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stays', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('relationship', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits', regex='^\\d{10}$')])),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['phone'], name='tenants_ten_phone_a45ee8_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['email'], name='tenants_ten_email_4879df_idx'),
        ),
        migrations.AddIndex(
            model_name='stay',
            index=models.Index(fields=['tenant', 'status'], name='tenants_sta_tenant__942098_idx'),
        ),
        migrations.AddIndex(
            model_name='stay',
            index=models.Index(fields=['bed', 'status'], name='tenants_sta_bed_id_e934a7_idx'),
        ),
        migrations.AddIndex(
            model_name='stay',
            index=models.Index(fields=['check_in'], name='tenants_sta_check_i_38d277_idx'),
        ),
        migrations.AddConstraint(
            model_name='stay',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['reserved', 'active'])), fields=('tenant',), name='uniq_active_reserved_stay_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='stay',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['reserved', 'active'])), fields=('bed',), name='uniq_active_reserved_stay_per_bed'),
        ),
        migrations.AddConstraint(
            model_name='emergencycontact',
            constraint=models.UniqueConstraint(fields=('tenant', 'phone'), name='uniq_tenant_emergency_phone'),
        ),
    ]
