# Generated by Django 5.2.5 on 2025-08-15 19:07

import django.core.validators
import tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='id_proof_document',
            field=models.FileField(blank=True, help_text='Upload an image (max 4 MB) or PDF (max 2 MB) for ID proof', null=True, upload_to='tenants/id_proofs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf']), tenants.models.validate_file_size]),
        ),
        migrations.DeleteModel(
            name='MaintenanceRequest',
        ),
    ]
