# Generated by Django 5.2.5 on 2025-08-15 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_bed_monthly_rent'),
        ('tenants', '0002_alter_tenant_id_proof_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='building',
            field=models.ForeignKey(blank=True, help_text='Home building for this tenant', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenants', to='properties.building'),
        ),
    ]
