# Generated by Django 5.2.5 on 2025-08-16 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_bed_monthly_rent'),
        ('tenants', '0003_tenant_building'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BedHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_on', models.DateField()),
                ('ended_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_history', to='properties.bed')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bed_history', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_on', '-created_at'],
                'indexes': [models.Index(fields=['tenant', 'bed'], name='idx_bedhist_tenant_bed'), models.Index(fields=['bed', 'started_on'], name='idx_bedhist_bed_start')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ended_on__isnull', True)), fields=('tenant', 'bed'), name='uniq_open_bedhistory_per_tenant_bed')],
            },
        ),
    ]
