# Generated by Django 5.2.5 on 2025-08-16 11:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_bed_monthly_rent'),
        ('tenants', '0004_bedhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BedHistory',
            new_name='TenantBedHistory',
        ),
    ]
