# Generated by Django 5.2.5 on 2025-08-16 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_rename_bedhistory_tenantbedhistory'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tenantbedhistory',
            table='tenant_bed_history',
        ),
    ]
