# Generated by Django 5.2.5 on 2025-08-16 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_alter_tenantbedhistory_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='BedHistory',
            fields=[
            ],
            options={
                'verbose_name': 'Bed history',
                'verbose_name_plural': 'Bed histories',
                'ordering': ['-started_on', '-created_at'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tenants.tenantbedhistory',),
        ),
    ]
