# Generated by Django 5.2.5 on 2025-08-18 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_bed_created_by_alter_bed_updated_by_and_more'),
        ('tenants', '0007_bedhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontact',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stay',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stay',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tenantbedhistory',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tenantbedhistory',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='StayBillingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('next_due_on', models.DateField(blank=True, null=True)),
                ('last_invoiced_period', models.CharField(blank=True, help_text='YYYY-MM', max_length=7)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('stay', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_state', to='tenants.stay')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BillingPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('org', 'Organization'), ('building', 'Building'), ('tenant', 'Tenant')], default='org', max_length=12)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('weekly', 'Weekly'), ('custom', 'Custom')], default='monthly', max_length=12)),
                ('due_day_type', models.CharField(choices=[('anniversary', 'Stay Check-in Anniversary'), ('fixed_dom', 'Fixed Day of Month'), ('weekday', 'Weekday in Month')], default='anniversary', max_length=20)),
                ('due_day_value', models.IntegerField(blank=True, help_text='For fixed_dom: 1-28. For weekday: 0-6 (Mon=0). Ignored for anniversary.', null=True)),
                ('weekday_nth', models.IntegerField(blank=True, help_text='For weekday: 1-5 for nth occurrence in month.', null=True)),
                ('grace_days', models.IntegerField(default=3)),
                ('remind_before_days', models.JSONField(default=list, help_text='List of days before due to remind, e.g., [3,1]')),
                ('overdue_repeat_days', models.IntegerField(default=3)),
                ('proration', models.CharField(default='none', max_length=12)),
                ('amount_source', models.CharField(choices=[('stay', 'Stay monthly_rent'), ('room', 'Room monthly_rent'), ('fixed', 'Fixed amount')], default='stay', max_length=12)),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('auto_generate_invoice', models.BooleanField(default=False)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_policies', to='properties.building')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('pg_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_policies', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_policies', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('scope', 'org')), fields=('pg_admin',), name='uniq_billing_policy_org_per_admin'), models.UniqueConstraint(condition=models.Q(('scope', 'building')), fields=('building',), name='uniq_billing_policy_per_building'), models.UniqueConstraint(condition=models.Q(('scope', 'tenant')), fields=('tenant',), name='uniq_billing_policy_per_tenant')],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(help_text='YYYY-MM', max_length=7)),
                ('due_on', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('canceled', 'Canceled')], default='open', max_length=12)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='properties.building')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='tenants.stay')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-due_on', '-created_at'],
                'indexes': [models.Index(fields=['stay', 'period'], name='idx_invoice_stay_period'), models.Index(fields=['building', 'status'], name='idx_invoice_building_status')],
                'constraints': [models.UniqueConstraint(fields=('stay', 'period'), name='uniq_invoice_stay_period')],
            },
        ),
    ]
