# Generated by Django 5.2.5 on 2025-08-18 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_alter_emergencycontact_created_by_and_more'),
    ]

    operations = [
        # Directly delete models instead of removing fields first to avoid
        # SQLite table remakes that reference dropped fields in indexes.
        migrations.DeleteModel(
            name='BillingPolicy',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='StayBillingState',
        ),
    ]
