# Generated by Django 5.2.5 on 2025-08-15 23:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0003_bed_monthly_rent'),
        ('tenants', '0003_tenant_building'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled'), ('no_show', 'No Show'), ('converted', 'Converted to Stay')], default='pending', max_length=12)),
                ('source', models.CharField(blank=True, choices=[('walkin', 'Walk-in'), ('phone', 'Phone'), ('online', 'Online'), ('other', 'Other')], default='walkin', max_length=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Optional end date for reservation window', null=True)),
                ('monthly_rent', models.DecimalField(decimal_places=2, default=0, help_text="Defaults from room's monthly rent; editable", max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0, help_text="Defaults from room's security deposit; editable", max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='Discount applied at booking (INR)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('maintenance_amount', models.DecimalField(decimal_places=2, default=0, help_text='Any maintenance charge applicable for this booking (INR)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='properties.bed')),
                ('booked_by', models.ForeignKey(blank=True, help_text='User who made this booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_booked', to=settings.AUTH_USER_MODEL)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='properties.building')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='properties.floor')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='properties.room')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('other', 'Other')], default='cash', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='success', max_length=12)),
                ('paid_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('reference', models.CharField(blank=True, help_text='Txn/Ref ID if applicable', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.booking')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-paid_on'],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['tenant', 'status'], name='bookings_bo_tenant__58bfba_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['bed', 'status'], name='bookings_bo_bed_id_385945_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['start_date'], name='bookings_bo_start_d_3e8155_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['floor'], name='bookings_bo_floor_i_c1d69e_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booked_at'], name='bookings_bo_booked__6ab0fd_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booked_by'], name='bookings_bo_booked__971099_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['building'], name='bookings_bo_buildin_66d925_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['room'], name='bookings_bo_room_id_2bee6f_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['booking', 'status'], name='bookings_pa_booking_bf00c8_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['paid_on'], name='bookings_pa_paid_on_2803eb_idx'),
        ),
    ]
