# Generated by Django 5.2.5 on 2025-08-16 00:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('properties', '0003_bed_monthly_rent'),
        ('tenants', '0003_tenant_building'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_no',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=30, unique=True),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_no'], name='bookings_bo_booking_839ec2_idx'),
        ),
    ]
