# Generated by Django 5.2.5 on 2025-08-16 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_booking_no_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_bo_booking_839ec2_idx',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booking_no',
        ),
    ]
