# Generated by Django 5.2.5 on 2025-08-16 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_bookingmovement'),
        ('properties', '0003_bed_monthly_rent'),
        ('tenants', '0003_tenant_building'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmovement',
            name='moved_by',
            field=models.ForeignKey(blank=True, help_text='User who performed this move', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_moves_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='bookingmovement',
            index=models.Index(fields=['moved_by'], name='bookings_bo_moved_b_05102e_idx'),
        ),
    ]
