# Generated by Django 5.2.5 on 2025-08-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_payment_billing_period_payment_stay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled'), ('converted', 'Converted to Stay'), ('checked_out', 'Checked Out')], default='pending', max_length=12),
        ),
    ]
