# Generated by Django 5.2.5 on 2025-08-18 20:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('properties', '0003_bed_monthly_rent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField(blank=True)),
                ('level', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=10)),
                ('subject_object_id', models.CharField(blank=True, max_length=64, null=True)),
                ('channels', models.JSONField(blank=True, default=list, help_text='e.g., ["in_app", "email"]')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('unread', models.BooleanField(db_index=True, default=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, help_text='User that performed the action (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_sent', to=settings.AUTH_USER_MODEL)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='properties.building')),
                ('pg_admin', models.ForeignKey(blank=True, help_text='Owning PG Admin for scoping', limit_choices_to={'role': 'pg_admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scoped_notifications', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(help_text='User that should see this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('subject_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'unread', '-created_at'], name='notif_rec_unread_idx'), models.Index(fields=['pg_admin', 'building', '-created_at'], name='notif_scope_idx'), models.Index(fields=['event', '-created_at'], name='notif_event_idx')],
            },
        ),
    ]
