# Generated by Django 5.2.5 on 2025-08-25 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_enabled', models.BooleanField(default=False)),
                ('whatsapp_provider', models.CharField(choices=[('none', 'None'), ('meta', 'Meta WhatsApp Cloud API'), ('twilio', 'Twilio WhatsApp'), ('custom', 'Custom Webhook')], default='none', max_length=16)),
                ('whatsapp_number', models.CharField(blank=True, help_text='E.164 format, e.g., +919876543210', max_length=32)),
                ('whatsapp_templates', models.JSONField(blank=True, default=dict)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(limit_choices_to={'role': 'pg_admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Settings',
                'verbose_name_plural': 'Notification Settings',
            },
        ),
    ]
