# Generated by Django 5.2.5 on 2025-08-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional notes about this building'),
        ),
        migrations.AddField(
            model_name='floor',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional notes about this floor'),
        ),
        migrations.AddField(
            model_name='room',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional notes about this room'),
        ),
    ]
