# Generated by Django 5.2.5 on 2025-08-15 16:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_building_notes_floor_notes_room_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='monthly_rent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
