# Generated by Django 5.2.5 on 2025-08-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_bed_created_by_alter_bed_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
