# Generated by Django 5.2.5 on 2025-08-24 13:31

import subscription.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='billing_interval',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='available_intervals',
            field=models.JSONField(blank=True, default=subscription.models.default_intervals, help_text="Allowed billing intervals for this plan (e.g., ['monthly','yearly'])"),
        ),
    ]
