# Generated by Django 5.2.5 on 2025-08-24 13:35

import subscription.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_subscription_billing_interval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='prices',
            field=models.JSONField(blank=True, default=dict, help_text="Map of interval code to price, e.g. {'1m': 499, '3m': 1299, '6m': 2399, '12m': 4499}"),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='billing_interval',
            field=models.CharField(default='1m', max_length=10),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='available_intervals',
            field=models.JSONField(blank=True, default=subscription.models.default_intervals, help_text="Allowed billing intervals codes e.g. ['1m','3m','6m','12m']"),
        ),
    ]
