# Generated by Django 5.2.5 on 2025-08-25 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_subscriptionplan_prices_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('discount_type', models.CharField(choices=[('percent', 'Percent'), ('amount', 'Fixed Amount')], default='percent', max_length=16)),
                ('value', models.DecimalField(decimal_places=2, help_text='Percent (0-100) or fixed amount depending on type', max_digits=10)),
                ('currency', models.CharField(default='INR', help_text='Used for fixed amount discounts', max_length=10)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('max_redemptions', models.PositiveIntegerField(blank=True, help_text='Global max uses (blank = unlimited)', null=True)),
                ('per_owner_limit', models.PositiveIntegerField(blank=True, help_text='Max uses per PG owner (blank = unlimited)', null=True)),
                ('allowed_plan_slugs', models.JSONField(blank=True, default=list, help_text='Empty = all plans')),
                ('allowed_intervals', models.JSONField(blank=True, default=list, help_text="Empty = all intervals (e.g. '1m','3m')")),
                ('is_active', models.BooleanField(default=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['code'], name='idx_coupon_code'), models.Index(fields=['is_active'], name='idx_coupon_active')],
            },
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='subscription.coupon')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_redemptions', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_redemptions', to='subscription.subscription')),
            ],
            options={
                'indexes': [models.Index(fields=['coupon_id', 'owner_id'], name='idx_coupon_owner'), models.Index(fields=['redeemed_at'], name='idx_coupon_redeemed_at')],
            },
        ),
    ]
