# Generated by Django 5.2.5 on 2025-08-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_coupon_couponredemption'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='base_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Base amount before discount', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='discount_code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='discount_currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('percent', 'Percent'), ('amount', 'Fixed Amount')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percent (0-100) or fixed amount depending on type', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='final_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Net after discount, before tax', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='gross_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='gst_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='gst_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
