# Generated by Django 5.2.5 on 2025-08-28 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_subscription_base_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='base_amount',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='discount_code',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='discount_currency',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='discount_type',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='discount_value',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='final_amount',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='gross_amount',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='gst_amount',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='gst_percent',
        ),
    ]
