# Generated by Django 5.2.5 on 2025-08-28 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_remove_subscription_base_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='discount_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='discount_allowed_intervals',
            field=models.JSONField(blank=True, default=list, help_text="Empty = all intervals (e.g. '1m','12m')"),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='discount_currency',
            field=models.CharField(default='INR', help_text='Used for fixed amount discounts', max_length=10),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='discount_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'Percent'), ('amount', 'Fixed Amount')], default='percent', max_length=16),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='discount_valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='discount_valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
