# Generated by Django 5.2.5 on 2025-08-17 16:03

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_expense_category_expensecategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='expensecategory',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='uniq_expensecategory_name_ci'),
        ),
    ]
