# Generated by Django 5.2.5 on 2025-08-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_expense_created_by_alter_expense_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='cycle_month',
            field=models.DateField(help_text='Cycle date for the billed month (YYYY-MM-DD), defaults to booking confirmation day'),
        ),
    ]
