# Generated by Django 5.2.5 on 2025-08-17 22:26

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_invoice_cycle_month'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='expensecategory',
            name='uniq_expensecategory_name_ci',
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='PG Admin who owns this category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paymentapp_expensecategory_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='expensecategory',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('owner'), name='uniq_expensecategory_owner_name_ci'),
        ),
    ]
