# Generated by Django 5.2.5 on 2025-08-19 08:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_invoicesettings'),
        ('properties', '0004_alter_bed_created_by_alter_bed_updated_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='expensecategory',
            name='unique_expensecategory_sequence_per_owner',
        ),
        migrations.RemoveConstraint(
            model_name='invoicesettings',
            name='uniq_invoicesettings_owner_building',
        ),
        migrations.AddConstraint(
            model_name='expensecategory',
            constraint=models.UniqueConstraint(fields=('owner', 'sequence'), name='unique_expensecategory_sequence_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='invoicesettings',
            constraint=models.UniqueConstraint(fields=('owner', 'building'), name='uniq_invoicesettings_owner_building'),
        ),
    ]
