# Generated by Django 5.2.5 on 2025-08-28 18:41

import tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_deduplicate_invoicesettings_before_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='expenses/attachments/', validators=[tenants.models.validate_file_size]),
        ),
    ]
